services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URL: mongodb://soheib:kaka1374@mongodb:27017/movie-crawler?authSource=admin
      OTP_BASE_URL: https://api.kavenegar.com/v1/6C39694C51414C477561396D656F314379567562717070734B6748676839717672585855424F48766C66593D/verify/lookup.json?
      PORT: 3000
      ACCESS_TOKEN_SECRET: 'secret'  
    networks:
      - app-network
    restart: on-failure   
  
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: soheib
      MONGO_INITDB_ROOT_PASSWORD: kaka1374
      MONGO_INITDB_DATABASE: movie-crawler
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
      - type: bind
        source: ./mongo-entrypoint
        target: /docker-entrypoint-initdb.d/
    healthcheck: 
      test: echo 'db.runCommand({find:"app_db_name.soheib"}).ok' | mongosh --authenticationDatabase admin --host localhost -u soheib -p kaka1374 admin --quiet | grep -q 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s  

volumes:
  mongo-data:
  
networks:
  app-network:
    driver: bridge  